#!/bin/sh

# Runs the Matlab Framework model simulation.  The inputs to this
# script at the various light, temperature and CO2 inputs to the
# simulation.

MATLAB_EXE=matlab

JOBS_DIR=../jobs

# Job id comes from command line
JOB_ID=$1

LIGHT_DAY=$2
LIGHT_NIGHT=$3
LIGHT_DAY_LENGTH=$4
LIGHT_TWILIGHT=$5

TEMP_DAY=$6
TEMP_NIGHT=$7
TEMP_DAY_LENGTH=$8
TEMP_TWILIGHT=$9

CO2_DAY=${10}
CO2_NIGHT=${11}
CO2_DAY_LENGTH=${12}
CO2_TWILIGHT=${13}

CLOCK_GENOTYPE=${14}

# Job directory
JOB_DIR=$JOBS_DIR/$JOB_ID
mkdir $JOB_DIR

# Copy the required files to the job directory
PARAM_FILE=$JOB_DIR/jobParams.m
echo "tempDay=$TEMP_DAY"               >> $PARAM_FILE
echo "tempNight=$TEMP_NIGHT"           >> $PARAM_FILE
echo "tempDayLength=$TEMP_DAY_LENGTH"  >> $PARAM_FILE
echo "tempTwilight=$TEMP_TWILIGHT"     >> $PARAM_FILE

echo "co2Day=$CO2_DAY"               >> $PARAM_FILE
echo "co2Night=$CO2_NIGHT"           >> $PARAM_FILE
echo "co2DayLength=$CO2_DAY_LENGTH"  >> $PARAM_FILE
echo "co2Twilight=$CO2_TWILIGHT"     >> $PARAM_FILE

echo "lightDay=$LIGHT_DAY"               >> $PARAM_FILE
echo "lightNight=$LIGHT_NIGHT"           >> $PARAM_FILE
echo "lightDayLength=$LIGHT_DAY_LENGTH"  >> $PARAM_FILE
echo "lightTwilight=$LIGHT_TWILIGHT"     >> $PARAM_FILE
echo "clockGenotype='$CLOCK_GENOTYPE'"   >> $PARAM_FILE

cat template.m >> $PARAM_FILE

# Run the simulation
cd $JOB_DIR
${MATLAB_EXE}  -nodesktop -nosplash -r "jobParams;exit"

# Wait for a while and then delete the directory - the application should pull it back quickly
# so there is no need to keep the data for very long.
sleep 120
cd ..
rm -r $JOB_DIR
